qlik-oss/catwalk

src/components/AppProvider.jsx, src/components/error-boundary.jsx, src/components/with-layout.jsx, src/components/with-model.jsx, src/index.jsx
Currently only used on highest level in the component tree. Can wrap individual components to protect them from crashing the whole application, other parts of the UI might still be possible to render.
=> Adds error boundary

package.json, src/components/AppProvider.jsx, src/components/error-boundary.jsx, src/enigma/config.js, src/enigma/get-doc.js, src/index.html
**Added URLSearchParams:**
http://localhost:1234/?app=drugcases
- hostname (default: localhost)
- port (default: 9076)
- app (required)
=> Use url search params

src/components/app-provider.jsx, src/components/field.jsx, src/components/filterbox.jsx, src/components/model.jsx, src/components/selections.jsx, src/components/with-model.jsx
=> Updating the model on app changes, e.g reloads

src/components/field.jsx, src/components/field.scss, src/components/filterbox.jsx, src/components/filterbox.scss, src/enigma/list-cache.js
Now fields are properly sorted in frequency order. During selection in a field the original order is retained. Once finished selecting the selected/optional ones will appear on top followed by excluded.
=> Sort by frequency and state including modal selection

README.md, package-lock.json, package.json, src/components/app.jsx, src/components/model.jsx, src/components/selections.jsx, src/components/selections.scss, src/components/topbar.jsx, src/components/topbar.scss, src/components/with-model.jsx
=> Adding topbar with logo and last reloaded info

src/components/error-boundary.jsx, src/components/model.jsx, src/components/model.scss, src/components/splash.css, src/components/splash.jsx
Fixes #67 
* Doc list max height solved
* Centered message that no data is loaded yet
* Use Splash component in error boundary too
=> Doc list max height solved

src/components/splash.jsx, src/components/splash.pcss
Adding small tool description
Changed app list look and feel to better allow for long descriptions
Fixing attached issue
=> Adding tool info minor UI change on splash screen

src/components/field.pcss, src/components/selection-field.jsx, src/components/selection-field.pcss, src/components/selections.jsx
Also adding ellipsis on field name when too long.
Closes #86
=> Closing filterbox in selections toolbar when scrolled outside parent container.

src/components/splash.jsx
=> Adding tagline to error views as well

src/components/use/column-options.js
=> Using id as name for dimensions and measures if no title is set

bookmark/bookmark.js, src/components/field.jsx, src/components/filterbox.jsx
=> Adding support for qIsOneAndOnlyOne-property on field

src/components/selection-field.jsx, src/components/table-field.jsx
=> Changed so that both table and selection field are sorted by states.

src/components/tooltip.jsx
=> Showing field and table comments in tooltips

src/components/table-field.pcss
=> Styling fixes to avoid rendering issue when layout has not yet been fetched

src/components/cube.jsx, src/components/cube.pcss, src/components/cubes.jsx, src/components/hypercube-table.jsx, src/components/hypercube-table.pcss
=> Add possibility to remove a column in the hybercube builder

src/components/hypercube-table.jsx, src/components/hypercube-table.pcss
=> Fixing bug with column and header mismatch in hypercube builder

src/components/filterbox.jsx, src/components/hypercube-table.jsx
=> Fixing bug with 0 not treated as numerics

package-lock.json, package.json, src/components/app.jsx, src/components/model.jsx, src/components/model.pcss
It might be a bit of a "hidden feature", since it's only visible when hovering over between tables.. but I like it that way.
=> Adding posibility to resize table columns

src/components/app.pcss, src/components/cube-column-chooser.pcss, src/components/cubes.pcss, src/components/field.pcss, src/components/filterbox.pcss, src/components/hypercube-table.pcss, src/components/model.jsx, src/components/model.pcss, src/components/selections.pcss, src/components/table-field.pcss, src/components/topbar.pcss, src/index.pcss
Also added css custom properties to index.pcss for some css being used all over catwalk.
=> Removes some magic numbers used for resizing of columns.

src/components/app-list.jsx, src/components/app.jsx, src/components/error-info.jsx, src/components/model.jsx, src/components/splash.jsx, src/components/topbar.jsx, src/enigma/config.js, src/util.js
This is a PR to solve #306.
I initially was going to just convert the http(s) to ws(s) in the config, but the resulting connection would be inconsistent with the string that was being shown in the URL, so instead I first updated the codebase so all these `engine_url` assignments would happen in one place, then I added the logic to convert. That way the URL shown is consistent with the URL being used to connect.
Happy Hacktoberfest
=> Convert http to ws

.eslintrc.json, package-lock.json, package.json, sense-extension/catwalk.js
Fixes https://github.com/qlik-oss/catwalk/issues/334
=> Add eslint-plugin-promise to devDependencies

.circleci/config.yml, package-lock.json, package.json, test/e2e/_setup.spec.js
The problem is that `DocID=$DocID npm run test:e2e` is started before `npm run start:cov &` is ready. We still need to spawn a new process for `parcel` but we need to add additional logic to handle the *async* behaviour...
=> Fix broken e2e build job

README.md, bookmark/bookmark.js, sense-extension/catwalk.js, src/components/error-info.jsx
partially fixes https://github.com/qlik-trial/core-trial/issues/277
=> fix: remove catwalk *.core.qlik.com refs

package-lock.json, src/components/app.jsx, src/components/splash.jsx, test/comp/__snapshots__/splash.test.jsx.snap, test/e2e/integration/doc-list.test.js
- adds a banner for announcing our intention of shuting dow the project
=> fix: prepare for archiving 
